[local]
localhost

[mongodb]
localhost

[catalogue]
catalogue-dev.daws88s.space

[redis]
localhost

[user]
catalogue-dev.daws88s.space

[cart]
catalogue-dev.daws88s.space

[mysql]
catalogue-dev.daws88s.space

[shipping]
catalogue-dev.daws88s.space

[rabbitmq]
catalogue-dev.daws88s.space

[payment]
catalogue-dev.daws88s.space

[frontend]
catalogue-dev.daws88s.space