[local]
localhost

[mongodb]
localhost

[catalogue]
catalogue-dev.daws88s.quest

[redis]
redis-dev.daws88s.quest

[user]
user-dev.daws88s.quest

[cart]
cart-dev.daws88s.quest

[mysql]
mysql-dev.daws88s.quest

[shipping]
shipping-dev.daws88s.quest

[rabbitmq]
rabbitmq-dev.daws88s.quest

[payment]
payment-dev.daws88s.quest

[frontend]
frontend-dev.daws88s.quest