- name: install MySQL server
  ansible.builtin.dnf:
    name: mysql-server
    state: present

- name: start and enable mysql server
  ansible.builtin.service:
    name: mysqld
    state: restarted
    enabled: yes

- name: install botocore and boto3
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
  - boto3
  - botocore    

- name: set mysql root password
  community.mysql.mysql_user:
    name: root
    host: localhost
    password: "{{ MYSQL_ROOT_PASSWORD }}"
    login_unix_socket: /var/lib/mysql/mysql.sock